elf: catch AttributeError thrown by pwnlib, as it doesn't support every ELF architecture. For example, when running BANG on barbet-ota-rd2a.210605.006-e56baaf5.zip the following error would be thrown:
AttributeError: AttributeError: arch ('em_qdsp6') must be one of ['aarch64', 'alpha', 'amd64', 'arm', 'avr', 'cris', 'i386', 'ia64', 'm68k', 'mips', 'mips64', 'msp430', 'none', 'powerpc', 'powerpc64', 'riscv32', 'riscv64', 's390', 'sparc', 'sparc64', 'thumb', 'vax']